$(document).ready(function(){
	$("a").click(function() {
		var hrefClicked = $(this).attr("href");
		if(hrefClicked.match("^#")) {
			var viewRequested = hrefClicked.substring(hrefClicked.indexOf("#") + 1);
			$(".is-active").removeClass("is-active");
			$("#"+viewRequested).addClass("is-active");
			$(".tablink_"+viewRequested).addClass("is-active");
		}
	});

	var userLang = navigator.language || navigator.userLanguage, countries = ['en', 'us', 'fr', 'de'], languages = ['en', 'us', 'fr', 'de'];

	var overview_header = "Overview";
	var theevent_header = "The Event";
	var therun_header = "The Run";
	var thelocation_header = "The Location";
	var media_header = "Media";
	var faq_header = "FAQ";
	var overview_theevent_text = "This event is intended as a birthday party to celebrate three birthdays. It is a public event, so everyone is welcome. There will be a 24h run, where participants donate a certain amount of money per kilometer they run. Furthermore there will be a small donation for every drink and piece of food sold.";
	var learn_more = "Learn more";
	var singlerun_header = "Single Run";
	var overview_singlerun_text = "Just as the name says, in this run you are on your own, but don't be afraid, you don't have to run for 24 hours straight ";
	var teamrun_header = "Team Run";
	var overview_teamrun_text = "The team run is intended to be 24 hours long, but teams don't have to run for a total of 24 hours ";
	var norun_header = "No Run";
	var overview_norun_text = "Just sit back, have a drink and enjoy the party! Please remember that you can also donate without running a single meter, although the satisfaction won't be that great.";
	var makeawish_text = "Make a Wish is an organization that aims to fulfill the wishes of children that have been diagnosed with an uncurable disease. You can checkout their website here: ";
	var sosvillagedenfantsmonde_text = "S.O.S. Village d'enfants monde focusses on building foster communities to offer a home to children that for whatever reason cannot enjoy growing up with their biological parents. Learn more at ";
	var theevent_intro = "On this page you should find all information you need regarding the event itself. If you are searching for information regarding the run, please visit ";
	var what = "What?";
	var why = "Why?";
	var when = "When?";
	var where = "Where?";
	var theevent_what1 = "Primarily this event is a birthday party to celebrate the following three birthdays:";
	var theevent_what2 = 'Secondarily, it is a public running event, with the goal being to collect money for "Make a Wish" and "S.O.S. Village d'+"'"+ 'Enfants Monde"'+"for every kilometer ran.";
	var theevent_what3 = "The events is over 24 hours long, while the run is exactly 24 hours. No-one is obliged to take part or stay on-site the whole time. However, those who want can stay there all the time, bring sleeping bags or just stay up. There's breakfast in the morning and meals during afternoon and evening. Drinks are of course also available. A part of the revenue generated by selling food and drinks is also going to the above-mentionned organisations.";
	var theevent_why1 = "We organized this party because we want to have a big celebration for these two special birthdays, 18 and 50. Plus, we thought this is a perfect opportunity to raise awareness that other people don't have the same luck as we do and help them at the same time.";
	var theevent_where1 = 'The party is set to take place at the "Stade Athlétique Schifflange", which can be found at the top end of "Montée du cimetière" in Schifflange';
	var theevent_when1 = "The event and the run will start on Friday evening at 8 pm. The run will end on Saturday evening at 8 pm, the party however will continue into the night to Sunday.";
	var therun_intro = "This page offers all the information you need to know if you want to participate in the run. If you are looking for information on the event itself, check out";
	var registration = "Registration";
	var participants = "Participants";
	var sections = "Sections";
	var contact = "Contact";
	var email_us = "Email us";
	var contact_form = "Contact form";

	if (userLang === "de") {

		$("#overview_header").text(overview_header_de);
		$("#theevent_header").text(theevent_header_de);
		$("#therun_header").text(therun_header_de);
		$("#thelocation_header").text(thelocation_header_de);
		$("#media_header").text(media_header_de);
		$("#faq_header").text(faq_header_de);
		$("#learn_more").text(learn_more_de);
		$("#overview_theevent_text").text(overview_theevent_text_de);
		$("#singlerun_header").text(singlerun_header_de);
		$("#overview_therun_singlerun_text").text(overview_therun_singlerun_text_de);
		$("#teamrun_header").text(teamrun_header_de);
		$("#overview_therun_teamrun_text").text(overview_therun_teamrun_text_de);
		$("#norun_header").text(norun_header_de);
		$("#overview_therun_norun_text").text(overview_therun_norun_text_de);
		$("#makeawish_text").text(makeawish_text_de);
		$("#sosvillagedenfantsmonde_text").text(sosvillagedenfantsmonde_text_de);
		$("#theevent_intro").text(theevent_intro_de);
		$("#this_page").text(this_page_de);
		$("#contents").text(contents_de);
		$("#what").text(what_de);
		$("#why").text(why_de);
		$("#when").text(when_de);
		$("#where").text(where_de);
		$("#theevent_what1").text(theevent_what1_de);
		$("#theevent_what2").text(theevent_what2_de);
		$("#theevent_what3").text(theevent_what3_de);
		$("#theevent_why1").text(theevent_why1_de);
		$("#theevent_when1").text(theevent_when1_de);
		$("#theevent_where1").text(theevent_where1_de);
		$("#therun_intro").text(therun_intro_de);
		$("#registration").text(registration_de);
		$("#participants").text(participants_de);
		$("#sections").text(sections_de);
		$("#contact").text(contacts_de);
		$("#email_us").text(email_us_de);
		$("#contact_form").text(contact_form_de);

	} else if (userLang === "fr") {

		$("#overview_header").text(overview_header_fr);
		$("#theevent_header").text(theevent_header_fr);
		$("#therun_header").text(therun_header_fr);
		$("#thelocation_header").text(thelocation_header_fr);
		$("#media_header").text(media_header_fr);
		$("#faq_header").text(faq_header_fr);
		$("#learn_more").text(learn_more_fr);
		$("#overview_theevent_text").text(overview_theevent_text_fr);
		$("#singlerun_header").text(singlerun_header_fr);
		$("#overview_therun_singlerun_text").text(overview_therun_singlerun_text_fr);
		$("#teamrun_header").text(teamrun_header_fr);
		$("#overview_therun_teamrun_text").text(overview_therun_teamrun_text_fr);
		$("#norun_header").text(norun_header_fr);
		$("#overview_therun_norun_text").text(overview_therun_norun_text_fr);
		$("#makeawish_text").text(makeawish_text_fr);
		$("#sosvillagedenfantsmonde_text").text(sosvillagedenfantsmonde_text_fr);
		$("#theevent_intro").text(theevent_intro_fr);
		$("#this_page").text(this_page_fr);
		$("#contents").text(contents_fr);
		$("#what").text(what_fr);
		$("#why").text(why_fr);
		$("#when").text(when_fr);
		$("#where").text(where_fr);
		$("#theevent_what1").text(theevent_what1_fr);
		$("#theevent_what2").text(theevent_what2_fr);
		$("#theevent_what3").text(theevent_what3_fr);
		$("#theevent_why1").text(theevent_why1_fr);
		$("#theevent_when1").text(theevent_when1_fr);
		$("#theevent_where1").text(theevent_where1_fr);
		$("#therun_intro").text(therun_intro_fr);
		$("#registration").text(registration_fr);
		$("#participants").text(participants_fr);
		$("#sections").text(sections_fr);
		$("#contact").text(contacts_fr);
		$("#email_us").text(email_us_fr);
		$("#contact_form").text(contact_form_fr);		
	}
})
